Repository boostcampwm2023/web08-ByeolSoop, pull requests merged in 2023-11, with the labels that each got.

#1 Docs: PR 템플릿 추가
  .github/pull_request_template.md
Labels: review, setting

#3 Feat: VSCode ESLint + prettier 설정 추가
  .gitignore
  BE/.eslintrc.js
  BE/.prettierrc
  BE/package-lock.json
  BE/package.json
  FE/.eslintrc.js
  FE/.prettierrc
  FE/package-lock.json
  FE/package.json
Labels: setting

#6 Feat: FE 환경 설정 추가
  FE/.eslintrc.js
  FE/.gitignore
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/App.css
  FE/src/App.js
  FE/src/index.css
  FE/src/index.js
  FE/src/reportWebVitals.js
  package-lock.json
Labels: front-end, setting

#11 [Feat] BE 환경 구축
  .gitignore
  BE/.eslintrc.js
  BE/nest-cli.json
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/configs/typeorm.config.ts
  BE/src/main.ts
  BE/test/app.e2e-spec.ts
  BE/test/jest-e2e.json
  BE/tsconfig.build.json
  BE/tsconfig.json
Labels: back-end, feat

#12 [Feat] 홈페이지 UI 제작
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
  FE/src/assets/background.png
  FE/src/assets/fonts/Pretendard-Bold.woff
  FE/src/assets/fonts/Pretendard-Medium.woff
  FE/src/assets/fonts/fonts.css
  FE/src/assets/logo.png
  FE/src/components/Header/Header.js
  FE/src/pages/HomePage.js
Labels: front-end, feat

#16 [Feat] User Entity 및 DTO 생성
  .gitignore
  BE/package-lock.json
  BE/package.json
  BE/src/configs/typeorm.config.ts
  BE/src/users/users.dto.ts
  BE/src/users/users.entitiy.ts
  BE/src/utils/enum.ts
Labels: back-end, feat

#17 [Feat] 로그인 화면 UI 구현
  FE/src/App.js
  FE/src/assets/kakao.png
  FE/src/assets/naver.png
  FE/src/atoms/headerAtom.js
  FE/src/components/Header/Header.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/ModalBackground.js/ModalBackground.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/pages/HomePage.js
  FE/src/pages/MainPage.js
Labels: front-end, feat

#19 [Feat] 회원가입 화면 UI 구현
  FE/.eslintrc.js
  FE/src/components/ModalBackground.js/ModalBackground.js
  FE/src/components/SignUpModal/SignUpModal.js
Labels: front-end, feat, UI/UX

#21 [Feat] 회원가입 API 구현
  BE/src/app.module.ts
  BE/src/configs/typeorm.config.ts
  BE/src/users/users.controller.ts
  BE/src/users/users.dto.ts
  BE/src/users/users.entity.ts
  BE/src/users/users.module.ts
  BE/src/users/users.repository.ts
  BE/src/users/users.service.ts
Labels: back-end, feat, fix, API

#23 [Feat] 일기 생성 모달 UI 구현
  FE/src/atoms/diaryAtom.js
  FE/src/components/DiaryModal/DiaryModal.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/pages/HomePage.js
Labels: front-end, feat, UI/UX

#25 [Chore] 로그인 UI 디자인 수정
  FE/src/components/DiaryModal/DiaryModal.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/styles/ModalButton.js
  FE/src/styles/ModalInputBox.js
  FE/src/styles/ModalTitle.js
  FE/src/styles/ModalWrapper.js
Labels: front-end, chore, UI/UX

#28 [Feat] Diary Entity 및 DTO 생성
  BE/src/configs/typeorm.config.ts
  BE/src/diaries/diaries.dto.ts
  BE/src/diaries/diaries.entity.ts
  BE/src/users/users.dto.ts
  BE/src/users/users.entity.ts
  BE/src/users/users.repository.ts
Labels: back-end, feat, fix, refactor

#31 [Feat] 모양, 태그 엔티티 생성
  BE/src/diaries/diaries.entity.ts
  BE/src/shapes/shapes.entity.ts
  BE/src/tags/tags.entity.ts
  BE/src/users/users.entity.ts
Labels: back-end, feat

#33 [Feat] Diary 초기 코드 템플릿 및 감정분석 컬럼 추가
  BE/src/app.module.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.entity.ts
  BE/src/diaries/diaries.module.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/src/utils/enum.ts
Labels: back-end, feat, chore

#36 [Feat] 다이어리 읽기 모달 UI 구현
  FE/src/atoms/diaryAtom.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/ModalBackground/ModalBackground.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/pages/HomePage.js
  FE/src/styles/ModalWrapper.js
Labels: front-end, feat, UI/UX

#37 [Feat] 일기 생성 API 구현
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
Labels: back-end, feat, API

#40 [Feat] 일기 읽기 API 구현
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
Labels: back-end, feat, API

#44 [Refactor] 중복 코드 최적화 및 파일 분리
  FE/.eslintrc.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/pages/HomePage.js
  FE/src/styles/Modal/DiaryModalHeader.js
  FE/src/styles/Modal/ModalButton.js
  FE/src/styles/Modal/ModalInputBox.js
  FE/src/styles/Modal/ModalTitle.js
  FE/src/styles/Modal/ModalWrapper.js
Labels: front-end, refactor, chore

#45 [Feat] 일기 삭제 DELETE API 구현
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
Labels: back-end, feat, API

#46 [Feat] 사이드바 UI 구현
  FE/src/App.js
  FE/src/assets/boostcamp.png
  FE/src/assets/side-bar.png
  FE/src/atoms/userAtom.js
  FE/src/components/Header/Header.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SideBar/SideBar.js
  FE/src/index.js
  FE/src/pages/HomePage.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, UI/UX

#49 [Feat] 일기 API CRUD e2e 테스트 코드 작성
  BE/src/configs/typeorm.config.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.service.ts
  BE/test/app.e2e-spec.ts
  BE/test/jest-e2e.json
Labels: back-end, fix, test

#51 [Feat] 일기 작성 모달 모양 선택 UI 추가
  FE/src/assets/stars.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, UI/UX

#53 [Deploy] Github Action을 통한 CI/CD 구축
  .github/workflows/deploy.yml
  BE/src/main.ts
Labels: back-end, deploy

#52 [Feat] 읽기 모달 UI에 수정, 삭제 버튼 추가 및 감정 분석 결과 추가
  FE/src/assets/delete.svg
  FE/src/assets/edit.svg
  FE/src/assets/indicator-arrow.svg
  FE/src/assets/star.svg
  FE/src/components/DiaryModal/DiaryReadModal.js
Labels: front-end, feat, UI/UX

#54 [Fix] FE 배포 코드 오류 수정
  .github/workflows/deploy.yml
Labels: back-end, fix, hotfix

#56 [Feat] 일기 삭제 모달 UI 구현
  FE/src/atoms/diaryAtom.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, UI/UX

#58 [Feat] 소개 페이지 영상 API 구현
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/introduce/introduce.controller.ts
  BE/src/introduce/introduce.module.ts
  BE/src/introduce/introduce.service.ts
  BE/src/utils/e3.ts
Labels: back-end, feat, API

#60 [Hotfix] 배포 스크립트 오류 수정
  .github/workflows/deploy.yml
Labels: hotfix

#61 [Feat] JWT를 활용한 인증 및 로그인 API 구현
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/dto/auth-access-token.dto.ts
  BE/src/auth/dto/auth-credential.dto.ts
  BE/src/auth/jwt.strategy.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.module.ts
  BE/src/users/users.controller.ts
  BE/src/users/users.dto.ts
  BE/src/users/users.entity.ts
  BE/src/users/users.module.ts
  BE/src/users/users.repository.ts
  BE/src/users/users.service.ts
Labels: back-end, feat, refactor, API

#63 [Feat] 타인의 일기 관련 기능에 대한 접근 막기
  BE/src/auth/auth.id-guard.ts
  BE/src/auth/auth.module.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.entity.ts
Labels: back-end, feat

#66 [Feat] 태그 기능 구현
  BE/src/diaries/diaries.dto.ts
  BE/src/diaries/diaries.entity.ts
  BE/src/diaries/diaries.module.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/src/tags/tags.controller.ts
  BE/src/tags/tags.entity.ts
  BE/src/tags/tags.module.ts
  BE/src/tags/tags.repository.ts
  BE/src/tags/tags.service.ts
Labels: back-end, feat, API

#69 [Feat] 일기 목업 데이터 작성 및 연결
  FE/public/data/data.json
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/index.js
Labels: front-end, feat

#70 [Feat] 기본 모양 객체 응답 및 uuid에 해당하는 모양 스트림 반환 API 구현
  BE/src/app.module.ts
  BE/src/auth/get-user.decorator.ts
  BE/src/shapes/shapes.controller.ts
  BE/src/shapes/shapes.default.ts
  BE/src/shapes/shapes.entity.ts
  BE/src/shapes/shapes.module.ts
  BE/src/shapes/shapes.repository.ts
  BE/src/shapes/shapes.service.ts
Labels: back-end, feat, refactor, API

#77 [Refactor] 사용자와 일기에 대한 엔티티, DTO 업데이트
  BE/src/app.module.ts
  BE/src/configs/typeorm.config.ts
  BE/src/diaries/diaries.dto.ts
  BE/src/diaries/diaries.entity.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/main.ts
  BE/src/users/users.dto.ts
  BE/src/users/users.entity.ts
Labels: back-end, fix, refactor

#78 [Hotfix] 마스터 유저 생성 실패 오류
  BE/src/users/users.repository.ts
Labels: back-end, hotfix

#84 [Feat] 로그인 데이터 연동 및 로그인 규칙 적용, accessToken 저장
  FE/src/atoms/userAtom.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SideBar/SideBar.js
  FE/src/styles/Modal/ModalButton.js
Labels: front-end, feat, fix

#85 [Feat] 일기 생성 API에 대한 서버 응답 수정 및 e2e 테스트 작성
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.dto.ts
  BE/src/main.ts
  BE/src/users/users.dto.ts
  BE/test/app.e2e-spec.ts
  BE/test/diaries.create.e2e-spec.ts
Labels: back-end, feat, test, API

#86 [Feat] 일기 생성 API 연동 및 입력 상태에 따른 저장 버튼 활성화
  FE/src/assets/deleteIcon.svg
  FE/src/components/DiaryModal/DiaryCreateModal.js
Labels: front-end, feat, UI/UX, API

#88 [Feat] 로그인 API에 대한 서버 응답 수정 및 e2e 테스트 작성
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/dto/auth-credential.dto.ts
  BE/src/auth/guard/auth.id-guard.ts
  BE/src/auth/guard/auth.user-guard.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/users/users.dto.ts
  BE/test/auth.signin.e2e-spec.ts
Labels: back-end, feat, refactor, test, API

#83 [Feat] 스트림 파일에 대해 StreamableFile 반환 기능 구현
  BE/package-lock.json
  BE/package.json
  BE/src/auth/auth.controller.ts
  BE/src/introduce/introduce.controller.ts
  BE/src/introduce/introduce.service.ts
  BE/src/shapes/shapes.controller.ts
  BE/src/shapes/shapes.service.ts
  BE/src/utils/e3.ts
Labels: back-end, feat, API

#92 [Feat] 전체 일기 목록 API 구현 및 e2e 테스트 작성
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.dto.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/test/diaries.read-list.e2e-spec.ts
Labels: back-end, feat, test, API

#94 [Fix] 일기 생성 시 태그 관련 동작에 비동기 처리 추가
  BE/src/diaries/diaries.service.ts
Labels: back-end, fix

#91 [Feat] 일기 나열 페이지 UI 구현
  FE/public/data/data.json
  FE/src/atoms/diaryAtom.js
  FE/src/atoms/headerAtom.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/Header/Header.js
  FE/src/components/SideBar/SideBar.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, UI/UX

#98 [Feat] 일기 나열 페이지 API 연동
  FE/src/assets/zoomIn.svg
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/styles/Modal/ModalWrapper.js
Labels: front-end, feat, UI/UX, API

#100 [Feat] 일기 삭제 API에 대한 서버 응답 수정 및 e2e 테스트 작성
  BE/src/auth/auth.module.ts
  BE/src/auth/guard/auth.diary-guard.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.dto.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/test/diaries.delete.e2e-spec.ts
Labels: back-end, feat, API

#102 [Feat] 일기 조회 API에 대한 서버 응답 수정 및 e2e 테스트 작성
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/src/diaries/dto/diaries.dto.ts
  BE/src/diaries/dto/diaries.read.dto.ts
  BE/test/diaries.delete.e2e-spec.ts
  BE/test/diaries.read.e2e-spec.ts
Labels: back-end, feat, refactor, chore, test, API

#106 [Feat] 일기 내용 암호화 기능 추가
  BE/src/diaries/diaries.service.ts
Labels: back-end, feat

#105 [Feat] 리스트 보기에서 자세히 보기 버튼 클릭 시 읽기 모달 연결
  FE/public/data/data.json
  FE/src/atoms/diaryAtom.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
Labels: front-end, feat, API

#107 [Feat] 일기 삭제 API 연동
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, API

#110 [Feat] 일기 로딩 애니메이션 구현
  FE/src/atoms/diaryAtom.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryLoadingModal.js
  FE/src/pages/MainPage.js
  FE/src/styles/Modal/LoadingAnimation.js
Labels: front-end, feat, UI/UX

#111 [Feat] 일기 수정 API에 대한 서버 응답 수정 및 e2e 테스트 작성
  BE/src/auth/guard/auth.diary-guard.ts
  BE/src/auth/guard/auth.jwt-guard.ts
  BE/src/auth/jwt.strategy.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/src/diaries/dto/diaries.dto.ts
  BE/src/shapes/shapes.controller.ts
  BE/test/e2e/auth.signin.e2e-spec.ts
  BE/test/e2e/diaries.create.e2e-spec.ts
  BE/test/e2e/diaries.delete.e2e-spec.ts
  BE/test/e2e/diaries.read-list.e2e-spec.ts
  BE/test/e2e/diaries.read.e2e-spec.ts
  BE/test/e2e/diaries.update.e2e-spec.ts
Labels: back-end, feat, fix, refactor, test, API

#114 [Fix] entity에서 uuid에 대해 unique 설정
  BE/src/diaries/diaries.entity.ts
  BE/src/shapes/shapes.entity.ts
  BE/src/users/users.entity.ts
Labels: back-end, fix

#117 [Feat] UI 애니메이션 추가
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/SideBar/SideBar.js
  FE/src/styles/Modal/ModalWrapper.js
Labels: front-end, feat, UI/UX

#120 [Fix] shape 객체가 존재하지 않을 경우 404 Not Found 에러가 되도록 수정
  BE/package.json
  BE/src/diaries/diaries.module.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/src/shapes/shapes.module.ts
  BE/src/tags/tags.repository.ts
  BE/test/e2e/auth.signin.e2e-spec.ts
  BE/test/e2e/diaries.create.e2e-spec.ts
  BE/test/e2e/diaries.delete.e2e-spec.ts
  BE/test/e2e/diaries.read-list.e2e-spec.ts
  BE/test/e2e/diaries.read.e2e-spec.ts
Labels: back-end, fix, refactor, test

#121 [Fix] 로딩 시 화면 깜빡임 수정
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
Labels: front-end, fix, chore

#122 [Feat] 배경 이미지 수정
  FE/src/assets/homeBackground.png
  FE/src/pages/HomePage.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, UI/UX

#124 [Fix] 모달 오른쪽 부분 빈 공간 삭제
  FE/src/components/DiaryModal/DiaryListModal.js
Labels: front-end, fix, UI/UX

#126 [Hotfix] 태그 찾을 때 비동기 처리로 인해 태그 생성 실패
  BE/src/diaries/diaries.service.ts
  BE/src/tags/tags.repository.ts
Labels: back-end, hotfix, API

#125 [Refactor] 일기 e2e 테스트 코드들을 통합 테스트 코드로 변환 후 일기 e2e 테스트 코드 작성
  BE/package.json
  BE/src/auth/guard/auth.jwt-guard.ts
  BE/test/e2e/diaries.e2e-spec.ts
  BE/test/int/auth.signin.int-spec.ts
  BE/test/int/diaries.create.int-spec.ts
  BE/test/int/diaries.delete.int-spec.ts
  BE/test/int/diaries.read-list.int-spec.ts
  BE/test/int/diaries.read.int-spec.ts
  BE/test/int/diaries.update.int-spec.ts
  BE/test/jest-int.json
Labels: back-end, refactor, test

#127 [Fix] 반응형 UI 수정
  FE/src/App.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/SideBar/SideBar.js
Labels: front-end, fix, UI/UX

#128 [Refactor] 회원가입 API URL 변경
  BE/src/app.module.ts
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/dto/users.dto.ts
  BE/src/auth/get-user.decorator.ts
  BE/src/auth/jwt.strategy.ts
  BE/src/auth/users.entity.ts
  BE/src/auth/users.repository.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/diaries/diaries.entity.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/src/shapes/shapes.controller.ts
  BE/src/shapes/shapes.entity.ts
  BE/src/shapes/shapes.module.ts
  BE/src/shapes/shapes.repository.ts
  BE/src/shapes/shapes.service.ts
  BE/src/users/users.controller.ts
  BE/src/users/users.module.ts
  BE/src/users/users.service.ts
  BE/test/int/diaries.read.int-spec.ts
  BE/test/int/diaries.update.int-spec.ts
Labels: back-end, refactor, API

#133 [Fix] 긴 일기 제목 UI 수정
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
Labels: front-end, fix, chore, UI/UX

#135 [Feat] 회원가입 API에 대한 서버 응답 수정 및 통합 테스트 작성
  BE/src/auth/auth.controller.ts
  BE/src/auth/dto/users.dto.ts
  BE/src/auth/users.entity.ts
  BE/test/int/auth.signup.int-spec.ts
Labels: back-end, feat, test, API

#136 [Feat] 로그인 유지 및 로그아웃 로직 변경 구현
  FE/src/App.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SideBar/SideBar.js
Labels: front-end, feat, API

#138 [Hotfix] Conflict Exception 오류 수정
  BE/src/auth/users.repository.ts
Labels: back-end, hotfix

#137 [Feat] 로그아웃 API에 대한 서버 응답 수정 및 통합 테스트 작성
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.service.ts
  BE/test/int/auth.signin.int-spec.ts
  BE/test/int/auth.signout.int-spec.ts
Labels: back-end, feat, test, API

#139 [Feat] 회원가입 API 연동
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/styles/Modal/ModalInputBox.js
Labels: front-end, feat, API

#140 [Hotfix] 일기 목록 오류 수정
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
Labels: back-end, hotfix

#146 [Fix] 읽기 모달 개행 문제 수정, 리스트 타이틀 넘침 시 말줄임표 추가
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
Labels: front-end, fix, chore, UI/UX

#147 [chore] 로그인 유지 박스 기능 추가, 회원가입 클릭 시 뷰 전환
  FE/src/App.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SideBar/SideBar.js
Labels: front-end, fix, chore

#151 [Hotfix] privateDiaryGuard 생성자 오류 수정
  BE/src/app.module.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/guard/auth.diary-guard.ts
Labels: back-end, hotfix

#153 [Hotfix] Shape 엔티티의 user에 eager loading 추가
  BE/src/shapes/shapes.entity.ts
Labels: back-end, hotfix

#155 [Feat] 일기 저장 시 감정 분석 결과 저장
  BE/package-lock.json
  BE/package.json
  BE/src/diaries/diaries.module.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/src/diaries/dto/diaries.sentiment.dto.ts
  BE/test/int/diaries.read.int-spec.ts
  BE/test/int/diaries.update.int-spec.ts
Labels: back-end, feat

#157 [Feat] 일기 작성, 읽기 모달에 아이콘 출력을 위한 API 연동
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
Labels: front-end, feat, UI/UX, API

#159 [Feat] history API 활용하여 이전, 이후 페이지 이동 구현
  FE/src/App.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/SideBar/SideBar.js
  FE/src/index.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, UI/UX

#164 [Perf] 모양 파일을 png에서 svg로 변경
  BE/src/shapes/shapes.controller.ts
  BE/src/shapes/shapes.default.ts
  BE/src/shapes/shapes.service.ts
  BE/src/utils/e3.ts
Labels: back-end, perf

#160 [Feat] 모양 목록 API 구현
  BE/src/shapes/shapes.controller.ts
  BE/src/shapes/shapes.repository.ts
  BE/src/shapes/shapes.service.ts
  BE/test/int/shape.read-list.int-spec.ts
Labels: back-end, feat, API

#167 [Deploy] Docker Image를 활용한 Github Action CI/CD 구축
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  docker/be/Dockerfile
  docker/fe/Dockerfile
Labels: back-end, deploy

#161 [Feat] 메인 페이지 3D뷰 구현 및 API 연동
  FE/package-lock.json
  FE/package.json
  FE/src/atoms/diaryAtom.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryLoadingModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/pages/MainPage.js
  FE/src/pages/StarPage.js
Labels: front-end, feat, UI/UX, API

#170 [Hotfix] eslint 오류 해결
  FE/.eslintrc.js
Labels: front-end, hotfix, setting

#172 [Deploy] ssh 접속 후 도커 재시작 스크립트 수정
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
Labels: back-end, deploy

#174 [Deploy] docker compose up 명령 실행 시 --build 옵션 제거
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
Labels: deploy

#176 [Fix] 사용자별 전체 모양 API로 변경
  FE/src/pages/MainPage.js
Labels: front-end, fix, API

#177 [Feat] 연도별 태그 순위 API 구현
  BE/src/app.module.ts
  BE/src/stat/dto/stat.tags.dto.ts
  BE/src/stat/stat.controller.ts
  BE/src/stat/stat.module.ts
  BE/src/stat/stat.service.ts
  BE/test/int/stat.service.int-spec.ts
Labels: back-end, feat, test, API

#179 [Hotfix] 감정 분석 결과 저장 오류 수정
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
Labels: back-end, hotfix

#180 [Feat] 별자리선 Entity 생성 및 API 구현
  BE/src/app.module.ts
  BE/src/diaries/diaries.controller.ts
  BE/src/lines/dto/lines.dto.ts
  BE/src/lines/lines.controller.ts
  BE/src/lines/lines.entity.ts
  BE/src/lines/lines.module.ts
  BE/src/lines/lines.repository.ts
  BE/src/lines/lines.service.ts
  BE/src/utils/data-transform.ts
Labels: back-end, feat, API

#181 [Test] 기존 테스트 코드 수정 및 단위, 통합 테스트 코드 작성
  BE/package.json
  BE/src/auth/dto/auth-credential.dto.spec.ts
  BE/src/auth/dto/users.dto.spec.ts
  BE/src/auth/dto/users.dto.ts
  BE/src/diaries/diaries.service.ts
  BE/src/diaries/dto/diaries.dto.spec.ts
  BE/src/introduce/introduce.service.ts
  BE/src/shapes/shapes.service.ts
  BE/src/utils/clearDb.ts
  BE/src/utils/s3.ts
  BE/test/e2e/auth.reissue.e2e-spec.ts
  BE/test/e2e/auth.signin.e2e-spec.ts
  BE/test/e2e/auth.signout.e2e-spec.ts
  BE/test/e2e/auth.signup.e2e-spec.ts
  BE/test/e2e/diaries.create.e2e-spec.ts
  BE/test/e2e/diaries.delete.e2e-spec.ts
  BE/test/e2e/diaries.e2e-spec.ts
  BE/test/e2e/diaries.read-list.e2e-spec.ts
  BE/test/e2e/diaries.read.e2e-spec.ts
  BE/test/e2e/diaries.update.e2e-spec.ts
  BE/test/e2e/shape.read-list.e2e-spec.ts
  BE/test/int/auth.service.int-spec.ts
  BE/test/int/diaries.repository.int-spec.ts
  BE/test/int/diaries.service.int-spec.ts
  BE/test/int/shapes.repository.int-spec.ts
  BE/test/int/shapes.service.int-spec.ts
  BE/test/int/tags.repository.int-spec.ts
  BE/test/int/user.repository.int-spec.ts
Labels: back-end, refactor, test

#182 [Hotfix] 만료된 액세스 토큰으로 요청 시 성공하도록 수정
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.service.ts
Labels: back-end, hotfix

#184 [Feat] 400번대 에러 핸들링 (401, 403)
  BE/src/auth/guard/auth.jwt-guard.ts
  BE/src/diaries/diaries.service.ts
  FE/.eslintrc.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/pages/MainPage.js
  FE/src/utils/utils.js
Labels: front-end, feat, API

#185 hotfix: 403 에러 시 홈페이지로 리다이렉션
  FE/src/pages/MainPage.js
Labels: front-end, hotfix

#186 [Feat] 별자리 편집 모드 구현
  FE/src/assets/arrow.svg
  FE/src/assets/hand.svg
  FE/src/assets/paint.svg
  FE/src/assets/stella.svg
  FE/src/atoms/starAtom.js
  FE/src/components/Button/SwitchButton.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/pages/MainPage.js
  FE/src/pages/StarPage.js
  FE/src/styles/Modal/ModalWrapper.js
Labels: front-end, feat, UI/UX, API

#187 [hotfix] 일기 수정 버그 고치기 위해 롤백
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
Labels: front-end, hotfix
