Repository boostcampwm2023/web08-ByeolSoop, pull requests merged in 2023-12, with the labels that each got.

#192 [Feat] 특정 연도에 대한 날짜별 일기 작성 통계 API 구현
  BE/src/stat/dto/stat.tags.dto.ts
  BE/src/stat/stat.controller.ts
  BE/src/stat/stat.service.ts
  BE/test/e2e/stat.diaries.e2e-spec.ts
  BE/test/int/stat.service.int-spec.ts
Labels: back-end, feat, API

#197 [Fix] 편집 모드 전환 시 모달이 닫히도록 수정
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/pages/StarPage.js
Labels: front-end, fix

#201 [Hotfix] 별자리선이 연결된 일기 삭제 시 별자리선도 함께 삭제
  BE/src/diaries/diaries.module.ts
  BE/src/diaries/diaries.repository.ts
Labels: back-end, hotfix, API

#203 [Fix] 일기 생성, 수정 시 Content 관련 오류 수정
  BE/src/diaries/diaries.service.ts
Labels: back-end, fix

#204 [Feat] 네이버 로그인
  BE/package-lock.json
  BE/package.json
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/strategies/jwt.strategy.ts
  BE/src/auth/strategies/naver.strategy.ts
  BE/src/auth/users.entity.ts
  BE/src/utils/enum.ts
Labels: back-end, feat, API

#207 [Chore] passport-naver 버전 낮추기
  BE/package-lock.json
  BE/package.json
  BE/src/auth/strategies/naver.strategy.ts
Labels: back-end, chore

#208 [Feat] 리스트 보기 필터링 기능 도입
  FE/package-lock.json
  FE/package.json
  FE/src/assets/search.svg
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
Labels: front-end, feat, UI/UX

#209 [Feat] 유료 디자인 구매 API 구현
  BE/src/app.module.ts
  BE/src/auth/users.entity.ts
  BE/src/purchase/dto/purchase.design.dto.ts
  BE/src/purchase/purchase.controller.ts
  BE/src/purchase/purchase.entity.ts
  BE/src/purchase/purchase.module.ts
  BE/src/purchase/purchase.repository.ts
  BE/src/purchase/purchase.service.ts
  BE/src/utils/enum.ts
Labels: back-end, feat, API

#210 [Chore] 회원가입 규칙 안내 및 로그인 규칙 어길 시 오류 메시지 통일화
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SignUpModal/SignUpModal.js
Labels: front-end, chore, UI/UX

#212 [Feat] 카카오 OAuth 로그인 API 구현
  BE/package-lock.json
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/strategies/kakao.strategy.ts
  BE/src/auth/strategies/naver.strategy.ts
  BE/src/auth/users.repository.ts
Labels: back-end, feat, refactor, API

#218 [Feat] 별 미리보기 색상 구현 + 리스트 보기 타이틀 꾸미기
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, refactor, UI/UX

#217 [Test] 네이버 로그인, 유료 디자인 구매 관련 테스트 코드 작성
  BE/package.json
  BE/src/purchase/dto/purchase.design.dto.ts
  BE/test/int/auth.service.int-spec.ts
  BE/test/int/purchase.service.int-spec.ts
  BE/test/jest-unit.json
  BE/test/unit/auth-credential.dto.unit-spec.ts
  BE/test/unit/diaries.dto.unit-spec.ts
  BE/test/unit/purchase.design.dto.unit-spec.ts
  BE/test/unit/users.dto.unit-spec.ts
Labels: back-end, test

#222 [Refactor] 로그인 API 응답 수정 및 리팩토링
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/dto/auth-access-token.dto.ts
Labels: back-end, refactor

#224 [Feat] 일기 작성, 수정 모양 선택 시 선택된 디자인 추가 및 변경
  FE/src/components/Button/SwitchButton.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/pages/StarPage.js
  FE/src/styles/Modal/ModalButton.js
  FE/src/styles/Modal/ModalWrapper.js
Labels: front-end, feat, fix, UI/UX

#219 [Feat] 일기 분석 페이지 UI 작성 및 API 연동
  FE/package-lock.json
  FE/package.json
  FE/src/assets/leftIcon.svg
  FE/src/assets/picket.svg
  FE/src/assets/rightIcon.svg
  FE/src/assets/toggleIcon.svg
  FE/src/atoms/diaryAtom.js
  FE/src/components/Button/SwitchButton.js
  FE/src/components/DiaryModal/Calendar.js
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryLoadingModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/DiaryModal/EmotionIndicator/DiaryEmotionIndicator.js
  FE/src/components/DiaryModal/EmotionIndicator/EmotionPicket.js
  FE/src/components/SideBar/SideBar.js
  FE/src/pages/HomePage.js
  FE/src/pages/MainPage.js
  FE/src/pages/StarPage.js
  FE/src/styles/Modal/DiaryModalHeader.js
  FE/src/styles/Modal/ModalWrapper.js
  FE/src/styles/Modal/Tag.js
  FE/src/utils/utils.js
Labels: front-end, feat, UI/UX, API

#226 [Feat] 광고 제거 구매 API 구현 및 통합테스트 작성
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/dto/auth-access-token.dto.ts
  BE/src/auth/dto/login-response.dto.ts
  BE/src/purchase/dto/purchase.credit.dto.ts
  BE/src/purchase/purchase.controller.ts
  BE/src/purchase/purchase.repository.ts
  BE/src/purchase/purchase.service.ts
  BE/test/int/auth.service.int-spec.ts
  BE/test/int/purchase.service.int-spec.ts
Labels: back-end, feat, refactor, test, API

#227 [Fix] 일기 분석 페이지 UI 수정
  FE/src/assets/logo-notext.svg
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
  FE/src/components/DiaryModal/EmotionIndicator/DiaryEmotionIndicator.js
Labels: front-end, fix, UI/UX

#228 [Fix] 일기 월별 통계 오류 해결
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
Labels: front-end, fix

#229 [Feat] 닉네임 받아서 로컬에 저장 및 메인페이지에 닉네임 출력
  FE/src/App.js
  FE/src/atoms/userAtom.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/SideBar/SideBar.js
  FE/src/pages/MainPage.js
Labels: front-end, feat, chore, UI/UX

#231 [Hotfix] naverStrategy profile 파싱 변경
  BE/src/auth/strategies/naver.strategy.ts
Labels: back-end, hotfix, API

#240 [Hotfix] 태그 입력 시 마지막 글자 중복 입력 오류 해결
  FE/src/components/DiaryModal/DiaryCreateModal.js
Labels: front-end, hotfix, UI/UX

#241 [Feat] 새 일기 작성 시 별가루 적립 및 조회 API 구현
  BE/src/auth/users.repository.ts
  BE/src/diaries/diaries.module.ts
  BE/src/diaries/diaries.repository.ts
  BE/src/diaries/diaries.service.ts
  BE/src/purchase/purchase.controller.ts
Labels: back-end, feat, API

#243 [Hotfix] CORS 에러 수정
  BE/src/auth/auth.controller.ts
  FE/src/App.js
Labels: front-end, back-end, hotfix

#245 [Fix] 4xx대 에러 응답 처리
  BE/package-lock.json
  FE/.eslintrc.js
  FE/public/maintest2.fbx
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/pages/MainPage.js
  FE/src/pages/StarPage.js
Labels: front-end, feat, fix, API

#246 [Fix] 개발 서버 로그인 에러 해결
  FE/src/pages/LoadingPage.js
Labels: front-end, fix

#247 [Fix] 결제 페이지 알럿창 추가
  FE/src/components/PurchaseModal/PurchaseModal.js
Labels: front-end, fix

#248 [Feat] UI 관련 피드백 적용
  FE/src/assets/rule.png
  FE/src/components/DiaryModal/Calendar.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryLoadingModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/components/SignUpModal/SignUpRuleGuide.js
  FE/src/pages/StarPage.js
  FE/src/styles/Modal/ModalTitle.js
Labels: front-end, feat, UI/UX

#252 [Fix] 리스트 보기 필터링 수정
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
Labels: front-end, feat, fix, chore, UI/UX

#253 [Deploy] 환경변수 저장 실패 hotfix
  .github/workflows/deploy-frontend.yml
Labels: deploy

#255 [Chore] 환경설정 대신 도움말로 변경, 홈페이지 배경화면 변경 등
  FE/public/homepage.mp4
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/Header/Header.js
  FE/src/components/SideBar/SideBar.js
  FE/src/pages/HomePage.js
  FE/src/pages/StarPage.js
Labels: front-end, chore, UI/UX

#257 [Fix] 클라이언트 IP를 환경에 따라 다르게 받도록 수정
  BE/src/auth/auth.service.ts
  BE/src/auth/guard/auth.jwt-guard.ts
Labels: back-end, fix

#262 [Fix] 리스트 보기에서 수정 시도 시 별이 원점으로 가는 이슈 수정
  FE/src/components/DiaryModal/DiaryListModal.js
Labels: front-end, fix

#259 [Chore] 유료 디자인 enum 수정
  BE/src/utils/enum.ts
Labels: back-end, chore

#264 [Feat] 별가루 API 연동 및 구매 기능 구현
  FE/src/atoms/userAtom.js
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
  FE/src/components/DiaryModal/DiaryPicket.js
  FE/src/components/PurchaseModal/PurchaseModal.js
  FE/src/components/SideBar/SideBar.js
  FE/src/pages/MainPage.js
  FE/src/pages/StarPage.js
Labels: front-end, feat, UI/UX, API

#266 [Fix] 403 에러 시 무한 알럿 발생 버그 수정
  FE/src/atoms/diaryAtom.js
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/DiaryModal/EmotionIndicator/DiaryEmotionIndicator.js
  FE/src/components/ModalBackground/ModalBackground.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/pages/MainPage.js
  FE/src/pages/Redirection.js
  FE/src/pages/StarPage.js
  FE/src/utils/utils.js
Labels: front-end, fix, UI/UX

#267 [Fix] 리스트 보기 달력 크기 버그 수정, 통계 페이지 잔디 크기 구현 방식 수정
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
Labels: front-end, fix, UI/UX

#269 [Test] 백엔드 통합 테스트 코드 트랜잭션 반영 및 테스트 DB 더미데이터 활용
  BE/package-lock.json
  BE/package.json
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.service.ts
  BE/src/diaries/dto/diaries.sentiment.dto.ts
  BE/src/purchase/purchase.repository.ts
  BE/src/purchase/purchase.service.ts
  BE/src/shapes/shapes.repository.ts
  BE/src/shapes/shapes.service.ts
  BE/src/tags/tags.repository.ts
  BE/test/int/auth.service.int-spec.ts
  BE/test/int/diaries.repository.int-spec.ts
  BE/test/int/diaries.service.int-spec.ts
  BE/test/int/purchase.repository.int-spec.ts
  BE/test/int/purchase.service.int-spec.ts
  BE/test/int/shapes.repository.int-spec.ts
  BE/test/int/shapes.service.int-spec.ts
  BE/test/int/stat.service.int-spec.ts
  BE/test/int/tags.repository.int-spec.ts
  BE/test/int/user.repository.int-spec.ts
Labels: back-end, refactor, test

#270 [Refactor] FE 코드 가독성 개선 등등 리팩토링
  FE/src/App.js
  FE/src/components/Button/SwitchButton.js
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryDeleteModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryReadModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/DiaryModal/EmotionIndicator/DiaryEmotionIndicator.js
  FE/src/components/DiaryModal/EmotionIndicator/EmotionPicket.js
  FE/src/components/LoginModal/LoginModal.js
  FE/src/components/PurchaseModal/PurchaseModal.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/constants/constants.js
  FE/src/index.js
  FE/src/pages/LoadingPage.js
  FE/src/pages/MainPage.js
  FE/src/pages/StarPage.js
  FE/src/utils/handleResponse.js
Labels: front-end, refactor

#273 Update README.md
  README.md
Labels: front-end, chore

#272 [Refactor] 컴포넌트 중복 요소 분리 및 정리
  FE/src/components/DiaryModal/DiaryAnalysisModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/PurchaseModal/PurchaseModal.js
  FE/src/components/SideBar/SideBar.js
  FE/src/components/SignUpModal/SignUpModal.js
  FE/src/styles/Modal/ModalInputBox.js
Labels: front-end, refactor

#271 [Test] 백엔드 e2e 테스트 코드 트랜잭션 반영 및 테스트 DB 더미데이터 활용
  BE/src/auth/guard/auth.diary-guard.ts
  BE/src/purchase/purchase.controller.ts
  BE/src/purchase/purchase.service.ts
  BE/src/utils/clearDb.ts
  BE/test/e2e/auth.reissue.e2e-spec.ts
  BE/test/e2e/auth.signin.e2e-spec.ts
  BE/test/e2e/auth.signout.e2e-spec.ts
  BE/test/e2e/auth.signup.e2e-spec.ts
  BE/test/e2e/diaries.create.e2e-spec.ts
  BE/test/e2e/diaries.delete.e2e-spec.ts
  BE/test/e2e/diaries.read-list.e2e-spec.ts
  BE/test/e2e/diaries.read.e2e-spec.ts
  BE/test/e2e/diaries.update.e2e-spec.ts
  BE/test/e2e/purchase.design-list.e2e-spec.ts
  BE/test/e2e/shape.read-list.e2e-spec.ts
  BE/test/e2e/stat.diaries.e2e-spec.ts
  BE/test/int/auth.service.int-spec.ts
  BE/test/int/shapes.repository.int-spec.ts
  BE/test/int/shapes.service.int-spec.ts
  BE/test/int/user.repository.int-spec.ts
Labels: back-end, fix, refactor, test

#275 [Feat] 샘플 계정 중복 로그인 허용
  BE/src/auth/guard/auth.jwt-guard.ts
Labels: back-end, feat

#276 [Hotfix] 별 이동 안 되는 문제 수정
  FE/src/pages/StarPage.js
Labels: hotfix

#277 [Fix] 헤더 css 수정
  FE/src/components/DiaryModal/DiaryCreateModal.js
  FE/src/components/DiaryModal/DiaryListModal.js
  FE/src/components/DiaryModal/DiaryUpdateModal.js
  FE/src/components/Header/Header.js
  FE/src/components/SideBar/SideBar.js
  FE/src/pages/MainPage.js
  FE/src/pages/StarPage.js
Labels: front-end, fix, UI/UX
